"""
AccelMark Leaderboard Generator
Reads all result.json files from results/ and generates leaderboard/site/leaderboard.js.

Usage:
    python leaderboard/generate.py
"""

import json
from pathlib import Path


RESULTS_DIR = Path("results")
SITE_DIR = Path("leaderboard/site")


def load_results() -> list[dict]:
    results = []
    for tier in ["verified", "community"]:
        tier_dir = RESULTS_DIR / tier
        if not tier_dir.exists():
            continue
        for submission_dir in sorted(tier_dir.iterdir()):
            result_path = submission_dir / "result.json"
            if not result_path.exists():
                continue
            try:
                with open(result_path) as f:
                    data = json.load(f)
                data["_tier"] = tier
                data["_submission_name"] = submission_dir.name
                results.append(data)
            except Exception as e:
                print(f"Warning: could not load {result_path}: {e}")
    return results


def extract_row(result: dict) -> dict:
    chip = result.get("chip", {})
    software = result.get("software", {})
    model = result.get("model", {})
    task = result.get("task", {})
    metrics = result.get("metrics", {})
    accuracy = result.get("accuracy", {})
    meta = result.get("meta", {})
    derived = metrics.get("derived", {})

    # Primary metric depends on scenario
    scenario = task.get("scenario")
    primary_metric = None
    primary_metric_label = None

    if scenario == "offline":
        offline = metrics.get("offline", {})
        rows = offline.get("results_by_batch_size", []) if offline else []
        valid = [r for r in rows if not r.get("oom")]
        if valid:
            primary_metric = max(r.get("throughput_tokens_per_sec", 0) for r in valid)
            primary_metric_label = "tokens/sec (offline)"
    elif scenario == "online":
        online = metrics.get("online", {})
        if online:
            primary_metric = online.get("max_valid_qps")
            primary_metric_label = "max valid QPS"
    elif scenario == "training":
        training = metrics.get("training", {})
        if training:
            primary_metric = training.get("tokens_per_sec")
            primary_metric_label = "tokens/sec (training)"

    return {
        "submission": result.get("_submission_name"),
        "tier": result.get("_tier"),
        "chip": chip.get("name"),
        "vendor": chip.get("vendor"),
        "chip_count": chip.get("count"),
        "framework": software.get("framework"),
        "model": model.get("model_id", "").split("/")[-1],
        "precision": model.get("precision"),
        "suite": result.get("suite_id"),
        "scenario": scenario,
        "primary_metric": primary_metric,
        "primary_metric_label": primary_metric_label,
        "accuracy_valid": accuracy.get("valid"),
        "accuracy_score": accuracy.get("subset_score"),
        "tokens_per_watt": derived.get("tokens_per_sec_per_watt"),
        "date": meta.get("date"),
        "submitted_by": meta.get("submitted_by"),
    }


def main():
    results = load_results()
    print(f"Loaded {len(results)} results.")

    rows = [extract_row(r) for r in results]

    SITE_DIR.mkdir(parents=True, exist_ok=True)
    out_path = SITE_DIR / "leaderboard.js"
    with open(out_path, "w") as f:
        f.write("// Auto-generated by leaderboard/generate.py. Do not edit manually.\n")
        f.write(f"const LEADERBOARD_DATA = {json.dumps(rows, indent=2)};\n")

    print(f"Leaderboard data written to {out_path} ({len(rows)} rows).")


if __name__ == "__main__":
    main()
