enable_tokenizer_batch_encode: true
continuous_decode_steps: 4
engine_kwargs:
  attention_backend: triton
  disable_cuda_graph_padding: true
  enable_piecewise_cuda_graph: true
  piecewise_cuda_graph_max_tokens: 1024
  prefill_attention_backend: fa3
